[[redirects]]
from = "/"
to = "/dist/html/index.html"
status = 200

[[redirects]]
from = "/features.html"
to = "/dist/html/features.html"
status = 200

[[redirects]]
from = "/contact.html"
to = "/dist/html/contact.html"
status = 200

[[redirects]]
from = "/index.html"
to = "/dist/html/index.html"
status = 200
